package vista;

import controlador.ConexionBD;
import controlador.ConsultasProductoProvedor;
import controlador.ConsultasVendedorVentas;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Compra;
import modelo.Producto;
import modelo.Proveedor;
import modelo.Vendedor;
import modelo.Venta;

/**
 *
 * @author Daniel
 */
public class adminVentas extends javax.swing.JFrame {

    /**
     * Creates new form adminVentas
     */
     //Variables para la consulta y conexion de la base de datos
    private PreparedStatement pstmt;
    private ResultSet resultado;
    private Connection con;
    private ConexionBD objBD;

    private int idProd = 0;
    private ArrayList<Double> total = new ArrayList<Double>();
    private ArrayList<Producto> productoCarrito = new ArrayList<Producto>();
    private ArrayList<String> cantidadCarrito = new ArrayList<String>();
    double totalMonto = 0;
    //Variables para la obtencion de la fecha de la pestaña de Registro
    private Calendar cal = Calendar.getInstance();
    private DateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
    public adminVentas() {
        initComponents();
        this.setTitle("Ventas");
        //Escribe la fecha en el jText de la fecha de la pestaña de Registro
        txtFecha.setText(formato.format(cal.getTime()).toString());
        try{
        ConsultasVendedorVentas buscar=new ConsultasVendedorVentas();
        ArrayList<Producto> pds = new ArrayList<Producto>();
        pds = buscar.arrayProductos();
        if (pds.isEmpty()) {  //Revisa que esté vacío
                    JOptionPane.showMessageDialog(null, "No existe Compra con ese ID");
                    //Establece el modelo de la tabla para que no sea editable
                    DefaultTableModel modelo = new DefaultTableModel(){
                        @Override
                        public boolean isCellEditable(int row, int column) {
                            return false;
                        }
                    };
                    //Aplica el modelo a la tabl
                    tablaProductos.setModel(modelo);
                    //Establece el nombre de las columnas
                    modelo.addColumn("Id Producto");
                    modelo.addColumn("Marca");
                    modelo.addColumn("Descripcion");
                    modelo.addColumn("Precio de Venta Menudeo");
                    modelo.addColumn("Precio de Venta Mayoreo");
                    modelo.addColumn("Existencias");
                } else {
                    //Establece el modelo de la tabla para que no sea editable
                    DefaultTableModel modelo = new DefaultTableModel() {
                        @Override
                        public boolean isCellEditable(int row, int column) {
                            return false;
                        }
                    };
                    //Establece el modelo de la tabla
                    tablaProductos.setModel(modelo);
                    //Establece las columnas de la tabla
                    modelo.addColumn("Id Producto");
                    modelo.addColumn("Marca");
                    modelo.addColumn("Descripcion");
                    modelo.addColumn("Precio de Venta Menudeo");
                    modelo.addColumn("Precio de Venta Mayoreo");
                    modelo.addColumn("Existencias");
                    //Crea un arreglo de objetos para llenar la tabla
                    Object[] o = null;
                    //Llena la tabla con las filas
                    for (int i = 0; i < pds.size(); i++) {
                        modelo.addRow(o);
                        modelo.setValueAt(pds.get(i).getId(), i, 0);
                        modelo.setValueAt(pds.get(i).getMarca(), i, 1);
                        modelo.setValueAt(pds.get(i).getDescripcion(), i, 2);
                        modelo.setValueAt(pds.get(i).getPrecioVentaMayoreo(), i, 3);
                        modelo.setValueAt(pds.get(i).getPrecioVentaMenudeo(), i, 4);
                        modelo.setValueAt(pds.get(i).getExistencias(), i, 5);
                    }
                }
        }catch(NullPointerException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Ocurrio un error ups");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        idVenCon = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        idCliCon = new javax.swing.JTextField();
        btnBusVen = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtidVenta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        btnBuscarVen = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtIdVendedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombreVendedor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtApellidoPVendedor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtApellidoMVendedor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        btnBuscarCli = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtApellidoPCliente = new javax.swing.JTextField();
        Registrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCarrito = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel16.setText("id Vendedor");

        jLabel17.setText("Buscar por Vendedor");

        jLabel18.setText("Buscar por Cliente");

        jLabel19.setText("id Cliente");

        btnBusVen.setText("Buscar");
        btnBusVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusVenActionPerformed(evt);
            }
        });

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id Venta", "Fecha", "Monto", "id Vendedor", "id Cliente"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel19))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idVenCon, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(idCliCon))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBusVen)
                            .addComponent(jButton4)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(633, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(idVenCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusVen))
                .addGap(20, 20, 20)
                .addComponent(jLabel18)
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(idCliCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar Ventas", jPanel2);

        jLabel1.setText("id Venta");

        txtidVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidVentaActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha");

        txtFecha.setEditable(false);

        jLabel3.setText("id Vendedor");

        txtMonto.setEditable(false);

        btnBuscarVen.setText("Buscar Vendedor");
        btnBuscarVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVenActionPerformed(evt);
            }
        });

        jLabel4.setText("Monto");

        jLabel5.setText("Datos Venta");

        jLabel6.setText("Datos Vendedor");

        jLabel7.setText("Apellido Materno");

        txtNombreVendedor.setEditable(false);

        jLabel8.setText("Apellido Paterno");

        txtApellidoPVendedor.setEditable(false);

        jLabel9.setText("Nombre");

        txtApellidoMVendedor.setEditable(false);

        jLabel11.setText("Datos Cliente");

        jLabel12.setText("Nombre");

        jLabel13.setText("Apellido Paterno");

        txtNombreCliente.setEditable(false);

        btnBuscarCli.setText("Buscar Cliente");
        btnBuscarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCliActionPerformed(evt);
            }
        });

        jLabel10.setText("id Cliente");

        txtApellidoPCliente.setEditable(false);

        Registrar.setText("Registrar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id Producto", "Marca", "Descripcion", "Precio"
            }
        ));
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        tablaCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id Producto", "Marca", "Descrpcion", "Total"
            }
        ));
        jScrollPane2.setViewportView(tablaCarrito);

        jLabel14.setText("Carrito");

        jLabel15.setText("Cantidad");

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente Invitado", "Cliente Preferente", "Cliente Estrella" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(465, 1276, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(87, 87, 87)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtidVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(27, 27, 27)))
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel12))))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNombreVendedor)
                                        .addComponent(txtApellidoMVendedor)
                                        .addComponent(txtApellidoPVendedor)
                                        .addComponent(txtIdCliente)
                                        .addComponent(txtNombreCliente)
                                        .addComponent(txtIdVendedor)
                                        .addComponent(txtApellidoPCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscarVen)
                                    .addComponent(btnBuscarCli))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(156, 156, 156)
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(44, 44, 44)
                                    .addComponent(Registrar))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                                .addComponent(jScrollPane2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(293, 293, 293)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)))
                        .addGap(110, 110, 110))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtidVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtIdVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarVen)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtApellidoPVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtApellidoMVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscarCli)
                            .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtApellidoPCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Registrar))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Registrar Ventas", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidVentaActionPerformed

    private void btnBuscarVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVenActionPerformed
         if (txtIdVendedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Ingresa un ID");//Valida que el campo no esté vacío
        } else {
            ConsultasVendedorVentas buscar = new  ConsultasVendedorVentas();
            try {
                //Llena los campos
                Vendedor vendedor = buscar.consultaVendedor(Integer.parseInt(txtIdVendedor.getText()));
                txtIdVendedor.setText(Integer.toString(vendedor.getId()));
                txtNombreVendedor.setText(vendedor.getNombre());
                txtApellidoPVendedor.setText(vendedor.getApp());
                txtApellidoMVendedor.setText(vendedor.getApm());
            } catch (NullPointerException e) {

            }
        }
    }//GEN-LAST:event_btnBuscarVenActionPerformed

    private void btnBuscarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCliActionPerformed
        int index = combo.getSelectedIndex();
        String nombre;
                    String app ;
            try{
            switch (index) {
                case 0:
                    txtIdCliente.setText("11111");
                    txtNombreCliente.setText("Invitado");
                    txtApellidoPCliente.setText("Invitado");
                    break;
                case 1:
                    pstmt = con.prepareStatement("select * from clientepreferente where id_cliente = ?");
                    pstmt.setInt(1, Integer.parseInt(txtIdCliente.getText()));
                    resultado = pstmt.executeQuery();  
                    nombre = resultado.getString("nombre");
                    app = resultado.getString("apP");
                    txtNombreCliente.setText(nombre);
                    txtApellidoPCliente.setText(app);
                    break;
                case 2:
                    pstmt = con.prepareStatement("select * from clienteestrella where id_cliente = ?");
                    pstmt.setInt(1, Integer.parseInt(txtIdCliente.getText()));
                    resultado = pstmt.executeQuery();  
                    nombre = resultado.getString("nombre");
                    app = resultado.getString("apP");
                    txtNombreCliente.setText(nombre);
                    txtApellidoPCliente.setText(app);
                    break;
            }
                
                
                
                
                
            }catch(SQLException e){
                System.out.print(e);
            }
        
    }//GEN-LAST:event_btnBuscarCliActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (txtCantidad.getText().isEmpty() || Integer.parseInt(txtCantidad.getText()) == 0 || idProd == 0) { //Verifica que los campos estén llenos
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        } else {
            ConsultasProductoProvedor buscar = new ConsultasProductoProvedor();
            Producto pr = new Producto();
            //Busca y mapea el producto
            pr = buscar.consultaProducto(idProd);
            //Añade el producto al carrito de compras
            productoCarrito.add(pr);
            if(txtIdCliente.getText().length()<=0){
                JOptionPane.showMessageDialog(null,"Ingrese un id de cliente antes de agregar productos al carrito");
                txtCantidad.setText("");
            }else{
                 if(txtIdCliente.getText().equals("11111")){
                    //Calcula el total de cada compra multiplicando el precio por la cantidad
                    total.add((pr.getPrecioVentaMenudeo() * Double.parseDouble(txtCantidad.getText())));
                    //Añade la cantidad productos al arreglo del carrito de compras
            cantidadCarrito.add(txtCantidad.getText());
                }else{
                    //Calcula el total de cada compra multiplicando el precio por la cantidad
                    total.add((pr.getPrecioVentaMayoreo() * Double.parseDouble(txtCantidad.getText())));
                    //Añade la cantidad productos al arreglo del carrito de compras
                    cantidadCarrito.add(txtCantidad.getText());
                }
                 //Crea la Tabla con un modelo para que no sea editable
                DefaultTableModel modelo = new DefaultTableModel() {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                };
                //Aplica el modelo
                tablaCarrito.setModel(modelo);
                //Crea las columnas de la tabla
                modelo.addColumn("Id Producto");
                modelo.addColumn("Marca");
                modelo.addColumn("Descripcion");
                modelo.addColumn("Total");
                //Crea un arreglo de objetos para las filas de la tabla
                Object[] o = null;
                //Llena la tabla con las filas
                for (int i = 0; i < productoCarrito.size(); i++) {
                    modelo.addRow(o);
                    modelo.setValueAt(productoCarrito.get(i).getId(), i, 0);
                    modelo.setValueAt(productoCarrito.get(i).getMarca(), i, 1);
                    modelo.setValueAt(productoCarrito.get(i).getDescripcion(), i, 2);
                    modelo.setValueAt("$" + total.get(i), i, 3);
                }
                //Calcula el total de la compra con base a el precio de los productos
                for (int i = 0; i < total.size(); i++) {
                    totalMonto += total.get(i);
                }
                //Pone el total en el jText
                txtMonto.setText("$ " + Double.toString(totalMonto));
            }
           
            
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
        //Averigua en qué fila se hizo click
        if (tablaProductos != null && tablaProductos.getModel() != null) { //Revisa que la tabla no esté vacía
            //Obtiene el numero de la fila y de la columna
            int row = tablaProductos.rowAtPoint(evt.getPoint());
            int col = tablaProductos.columnAtPoint(evt.getPoint());
            if (tablaProductos.getValueAt(row, col) != null) {
                String st = tablaProductos.getModel().getValueAt(row, 0).toString();
                System.out.println(st);
                idProd = Integer.parseInt(st);
            }

        }
    }//GEN-LAST:event_tablaProductosMouseClicked

    private void btnBusVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusVenActionPerformed
        ConsultasVendedorVentas f=new ConsultasVendedorVentas(); 
        int id=Integer.parseInt(idVenCon.getText());
        try {
            f.llenarTabla(jTable1,id);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }         
    }//GEN-LAST:event_btnBusVenActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ConsultasVendedorVentas f=new ConsultasVendedorVentas(); 
        int id=Integer.parseInt(idCliCon.getText());
        try {
            f.llenarTabla2(jTable1,id);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }   
    }//GEN-LAST:event_jButton4ActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        ConsultasVendedorVentas registro = new ConsultasVendedorVentas();
        if (txtidVenta.getText().isEmpty()) { //Verifica que los campos estén llenos
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        } else {
            try {
                //Crea variables de fecha para guardar los datos en la Base
                java.util.Date date = new java.util.Date();
                java.sql.Date sqlDate = new java.sql.Date(date.getTime());
                if (registro.altaVenta(Integer.parseInt(txtidVenta.getText()), sqlDate, totalMonto,Integer.parseInt(txtIdVendedor.getText()),Integer.parseInt(txtIdCliente.getText()))) { // Verifica el Alta
                    JOptionPane.showMessageDialog(null, "Registro Exitoso");
                }
            } catch (NullPointerException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_RegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registrar;
    private javax.swing.JButton btnBusVen;
    private javax.swing.JButton btnBuscarCli;
    private javax.swing.JButton btnBuscarVen;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JTextField idCliCon;
    private javax.swing.JTextField idVenCon;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tablaCarrito;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtApellidoMVendedor;
    private javax.swing.JTextField txtApellidoPCliente;
    private javax.swing.JTextField txtApellidoPVendedor;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdVendedor;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreVendedor;
    private javax.swing.JTextField txtidVenta;
    // End of variables declaration//GEN-END:variables
}
