/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ConsultasCliente;
import javax.swing.JOptionPane;
import modelo.ClienteEstrella;
import modelo.ClientePreferente;

/**
 *
 * @author Ale
 */
public class adminClientes extends javax.swing.JFrame {

    /**
     * Creates new form administrarClientes
     */
    public adminClientes() {
        initComponents();
        this.setTitle("Administración Clientes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelEstrella = new javax.swing.JPanel();
        lblId1 = new javax.swing.JLabel();
        txtId1 = new javax.swing.JTextField();
        btnBuscar1 = new javax.swing.JButton();
        lblNombre1 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        BtnAgregar1 = new javax.swing.JButton();
        btnModificar1 = new javax.swing.JButton();
        txtApP1 = new javax.swing.JTextField();
        lblApP1 = new javax.swing.JLabel();
        lblApM1 = new javax.swing.JLabel();
        txtApM1 = new javax.swing.JTextField();
        BtnEliminar1 = new javax.swing.JButton();
        lblPromo1 = new javax.swing.JLabel();
        txtPromo1 = new javax.swing.JTextField();
        lblMontoHC = new javax.swing.JLabel();
        txtMontoH = new javax.swing.JTextField();
        btnLimpiar1 = new javax.swing.JButton();
        panelPreferente = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblApP = new javax.swing.JLabel();
        lblApM = new javax.swing.JLabel();
        lblPromo = new javax.swing.JLabel();
        lblMontoCredito = new javax.swing.JLabel();
        lblAdeudo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApM = new javax.swing.JTextField();
        txtApP = new javax.swing.JTextField();
        txtMontoC = new javax.swing.JTextField();
        txtPromo = new javax.swing.JTextField();
        txtAdeudo = new javax.swing.JTextField();
        BtnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblId1.setText("Id:");

        txtId1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtId1KeyTyped(evt);
            }
        });

        btnBuscar1.setText("Buscar");
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });

        lblNombre1.setText("Nombre:");

        txtNombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombre1KeyTyped(evt);
            }
        });

        BtnAgregar1.setText("Agregar");
        BtnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregar1ActionPerformed(evt);
            }
        });

        btnModificar1.setText("Modificar");
        btnModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar1ActionPerformed(evt);
            }
        });

        txtApP1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApP1KeyTyped(evt);
            }
        });

        lblApP1.setText("Apellido Paterno:");

        lblApM1.setText("Apellido Materno:");

        txtApM1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApM1KeyTyped(evt);
            }
        });

        BtnEliminar1.setText("Eliminar");
        BtnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminar1ActionPerformed(evt);
            }
        });

        lblPromo1.setText("Promociones: ");

        txtPromo1.setEditable(false);
        txtPromo1.setText("No cuenta con promociones");
        txtPromo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPromo1ActionPerformed(evt);
            }
        });

        lblMontoHC.setText("Monto Historico:");

        txtMontoH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoHKeyTyped(evt);
            }
        });

        btnLimpiar1.setText("Limpiar Campos");
        btnLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEstrellaLayout = new javax.swing.GroupLayout(panelEstrella);
        panelEstrella.setLayout(panelEstrellaLayout);
        panelEstrellaLayout.setHorizontalGroup(
            panelEstrellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstrellaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelEstrellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEstrellaLayout.createSequentialGroup()
                        .addComponent(lblMontoHC)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelEstrellaLayout.createSequentialGroup()
                        .addGroup(panelEstrellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelEstrellaLayout.createSequentialGroup()
                                .addGroup(panelEstrellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPromo1)
                                    .addComponent(lblApM1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelEstrellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApM1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMontoH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPromo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelEstrellaLayout.createSequentialGroup()
                                .addComponent(lblApP1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtApP1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelEstrellaLayout.createSequentialGroup()
                                .addGroup(panelEstrellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNombre1)
                                    .addComponent(lblId1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelEstrellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelEstrellaLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscar1))
                                    .addGroup(panelEstrellaLayout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addGroup(panelEstrellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnModificar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnAgregar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnEliminar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEstrellaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        panelEstrellaLayout.setVerticalGroup(
            panelEstrellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstrellaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelEstrellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar1))
                .addGap(25, 25, 25)
                .addGroup(panelEstrellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre1)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAgregar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEstrellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApP1)
                    .addComponent(txtApP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEstrellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApM1)
                    .addComponent(txtApM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEliminar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEstrellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPromo1)
                    .addComponent(txtPromo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEstrellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMontoHC)
                    .addComponent(txtMontoH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnLimpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jTabbedPane1.addTab("Cliente Estrella", panelEstrella);

        lblId.setText("Id:");

        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre:");

        lblApP.setText("Apellido Paterno:");

        lblApM.setText("Apellido Materno:");

        lblPromo.setText("Promociones: ");

        lblMontoCredito.setText("Monto de Credito:");

        lblAdeudo.setText("Adeudo:");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtApM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApMKeyTyped(evt);
            }
        });

        txtApP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApPKeyTyped(evt);
            }
        });

        txtMontoC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoCKeyTyped(evt);
            }
        });

        txtPromo.setEditable(false);
        txtPromo.setText("Si cuenta con promociones");
        txtPromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPromoActionPerformed(evt);
            }
        });

        txtAdeudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdeudoActionPerformed(evt);
            }
        });
        txtAdeudo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAdeudoKeyTyped(evt);
            }
        });

        BtnAgregar.setText("Agregar");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar Campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPreferenteLayout = new javax.swing.GroupLayout(panelPreferente);
        panelPreferente.setLayout(panelPreferenteLayout);
        panelPreferenteLayout.setHorizontalGroup(
            panelPreferenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreferenteLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelPreferenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPreferenteLayout.createSequentialGroup()
                        .addComponent(lblMontoCredito)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelPreferenteLayout.createSequentialGroup()
                        .addGroup(panelPreferenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelPreferenteLayout.createSequentialGroup()
                                .addComponent(lblAdeudo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAdeudo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPreferenteLayout.createSequentialGroup()
                                .addGroup(panelPreferenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPromo)
                                    .addComponent(lblApM))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelPreferenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMontoC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPromo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelPreferenteLayout.createSequentialGroup()
                                .addComponent(lblApP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtApP, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPreferenteLayout.createSequentialGroup()
                                .addGroup(panelPreferenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNombre)
                                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelPreferenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelPreferenteLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscar))
                                    .addGroup(panelPreferenteLayout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(panelPreferenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPreferenteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        panelPreferenteLayout.setVerticalGroup(
            panelPreferenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreferenteLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelPreferenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(25, 25, 25)
                .addGroup(panelPreferenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPreferenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApP)
                    .addComponent(txtApP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPreferenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApM)
                    .addComponent(txtApM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPreferenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPromo)
                    .addComponent(txtPromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPreferenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMontoCredito)
                    .addComponent(txtMontoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPreferenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdeudo)
                    .addComponent(txtAdeudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jTabbedPane1.addTab("Cliente Preferente", panelPreferente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPromoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPromoActionPerformed

    private void txtAdeudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdeudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdeudoActionPerformed

    private void txtPromo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPromo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPromo1ActionPerformed

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
         char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "ingresar solo numeros");
        }
    }//GEN-LAST:event_txtIdKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "ingresar solo letras");
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApPKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "ingresar solo letras");
        }
    }//GEN-LAST:event_txtApPKeyTyped

    private void txtApMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApMKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "ingresar solo letras");
        }
    }//GEN-LAST:event_txtApMKeyTyped

    private void txtId1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtId1KeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "ingresar solo numeros");
        }
    }//GEN-LAST:event_txtId1KeyTyped

    private void txtMontoCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoCKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "ingresar solo numeros");
        }
        if (evt.getKeyChar() == '.' && txtMontoC.getText().contains(".")) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "ya hay un punto decimal");
        }
    }//GEN-LAST:event_txtMontoCKeyTyped

    private void txtAdeudoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdeudoKeyTyped
        
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "ingresar solo numeros");
        }
        if (evt.getKeyChar() == '.' && txtAdeudo.getText().contains(".")) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "ya hay un punto decimal");
        }
    }//GEN-LAST:event_txtAdeudoKeyTyped

    private void txtNombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre1KeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "ingresar solo letras");
        }
    }//GEN-LAST:event_txtNombre1KeyTyped

    private void txtApP1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApP1KeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "ingresar solo letras");
        }
    }//GEN-LAST:event_txtApP1KeyTyped

    private void txtApM1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApM1KeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "ingresar solo letras");
        }
    }//GEN-LAST:event_txtApM1KeyTyped

    private void txtMontoHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoHKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "ingresar solo numeros");
        }
        if (evt.getKeyChar() == '.' && txtMontoH.getText().contains(".")) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "ya hay un punto decimal");
        }
    }//GEN-LAST:event_txtMontoHKeyTyped

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        if (txtId1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Ingresa un ID"); //valida que el campo id no este vacio
        }else{
            ConsultasCliente buscar = new ConsultasCliente();  //Se conecta a la Base de datos
            ClienteEstrella clienteE = buscar.consultaClienteE(Integer.parseInt(txtId1.getText())); //regresa un objeto con los datos de la consulta
            //Asigna valores a los campos de texto
            try {
                txtNombre1.setText(clienteE.getNombre()); 
                txtApP1.setText(clienteE.getApellidoPaterno());
                txtApM1.setText(clienteE.getApellidoMaterno());
                txtMontoH.setText(String.valueOf(clienteE.getMontoHistoricoCompra()));
            } catch (NullPointerException e) {
                System.out.println("No se puedieron llenar los campos");
            }
            
        } 
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void BtnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregar1ActionPerformed
        if (txtId1.getText().isEmpty() || txtNombre1.getText().isEmpty() || txtApP1.getText().isEmpty() || txtApM1.getText().isEmpty() || txtMontoH.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "llena todos los campos"); //valida que no haya campos vacios  
        }else{
            ConsultasCliente alta = new ConsultasCliente();  //Se conecta a la Base de datos
            ClienteEstrella clienteE = new ClienteEstrella();
            // Toma los datos de los campos de texto
            clienteE.setId(Integer.parseInt(txtId1.getText()));
            clienteE.setNombre(txtNombre1.getText());
            clienteE.setApellidoPaterno(txtApP1.getText());
            clienteE.setApellidoMaterno(txtApM1.getText());
            clienteE.setMontoHistoricoCompra(Double.parseDouble(txtMontoH.getText()));
            clienteE.setPromociones(false);
            if (alta.altaClienteE(clienteE)) {//Realiza el Alta 
                JOptionPane.showMessageDialog(rootPane, "Registro Exitoso");
            }
        }
    }//GEN-LAST:event_BtnAgregar1ActionPerformed

    private void btnModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar1ActionPerformed
        if (txtId1.getText().isEmpty() || txtNombre1.getText().isEmpty() || txtApP1.getText().isEmpty() || txtApM1.getText().isEmpty() || txtMontoH.getText().isEmpty()) {
           JOptionPane.showMessageDialog(rootPane, "llena todos los campos"); //valida que no haya campos vacios 
        }else{
            ConsultasCliente update = new ConsultasCliente();  //Se conecta a la Base de datos
            ClienteEstrella clienteE = new ClienteEstrella();
            // Toma los datos de los campos de texto
            clienteE.setId(Integer.parseInt(txtId1.getText()));
            clienteE.setNombre(txtNombre1.getText());
            clienteE.setApellidoPaterno(txtApP1.getText());
            clienteE.setApellidoMaterno(txtApM1.getText());
            clienteE.setMontoHistoricoCompra(Double.parseDouble(txtMontoH.getText()));
            clienteE.setPromociones(false);
            if (update.modicaClienteE(clienteE)) {//Realiza el Alta 
                JOptionPane.showMessageDialog(rootPane, "Actualizacion Exitosa");
            }
        }
    }//GEN-LAST:event_btnModificar1ActionPerformed

    private void BtnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminar1ActionPerformed
        if (txtId1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Ingresa un ID"); //valida que el campo id no este vacio
        }else{
            int id = Integer.parseInt(txtId1.getText());
            ConsultasCliente eliminar = new ConsultasCliente();  //Se conecta a la Base de datos
            if (eliminar.eliminaCliente(id)) {
                JOptionPane.showMessageDialog(rootPane, "Se elimino este registro");
            }
        }
    }//GEN-LAST:event_BtnEliminar1ActionPerformed

    private void btnLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar1ActionPerformed
        txtId1.setText("");
        txtNombre1.setText("");
        txtApP1.setText("");
        txtApM1.setText("");
        txtMontoH.setText("");
    }//GEN-LAST:event_btnLimpiar1ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Ingresa un ID"); //valida que el campo id no este vacio
        }else{
            ConsultasCliente buscar = new ConsultasCliente();  //Se conecta a la Base de datos
            ClientePreferente clienteP = buscar.consultaClienteP(Integer.parseInt(txtId.getText())); //regresa un objeto con los datos de la consulta
            //Asigna valores a los campos de texto
            try {
                txtNombre.setText(clienteP.getNombre()); 
                txtApP.setText(clienteP.getApellidoPaterno());
                txtApM.setText(clienteP.getApellidoMaterno());
                txtMontoC.setText(String.valueOf(clienteP.getMontoCredito()));
                txtAdeudo.setText(String.valueOf(clienteP.getAdeudo()));
            } catch (NullPointerException e) {
                System.out.println("No se puedieron llenar los campos");
            }
            
        } 
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        if (txtId.getText().isEmpty() || txtNombre.getText().isEmpty() || txtApP.getText().isEmpty() || txtApM.getText().isEmpty() || txtMontoC.getText().isEmpty() || txtAdeudo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "llena todos los campos"); //valida que no haya campos vacios  
        }else{
            ConsultasCliente alta = new ConsultasCliente();  //Se conecta a la Base de datos
            ClientePreferente clienteP = new ClientePreferente();
            // Toma los datos de los campos de texto
            clienteP.setId(Integer.parseInt(txtId.getText()));
            clienteP.setNombre(txtNombre.getText());
            clienteP.setApellidoPaterno(txtApP.getText());
            clienteP.setApellidoMaterno(txtApM.getText());
            clienteP.setMontoCredito(Double.parseDouble(txtMontoC.getText()));
            clienteP.setAdeudo(Double.parseDouble(txtAdeudo.getText()));
            clienteP.setPromociones(true);
            if (alta.altaClienteP(clienteP)) {//Realiza el Alta 
                JOptionPane.showMessageDialog(rootPane, "Registro Exitoso");
            }
        }
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (txtId.getText().isEmpty() || txtNombre.getText().isEmpty() || txtApP.getText().isEmpty() || txtApM.getText().isEmpty() || txtMontoC.getText().isEmpty() || txtAdeudo.getText().isEmpty()) {
           JOptionPane.showMessageDialog(rootPane, "llena todos los campos"); //valida que no haya campos vacios 
        }else{
            ConsultasCliente update = new ConsultasCliente();  //Se conecta a la Base de datos
            ClientePreferente clienteP = new ClientePreferente();
            // Toma los datos de los campos de texto
            clienteP.setId(Integer.parseInt(txtId.getText()));
            clienteP.setNombre(txtNombre.getText());
            clienteP.setApellidoPaterno(txtApP.getText());
            clienteP.setApellidoMaterno(txtApM.getText());
            clienteP.setMontoCredito(Double.parseDouble(txtMontoC.getText()));
            clienteP.setAdeudo(Double.parseDouble(txtAdeudo.getText()));
            clienteP.setPromociones(true);
            if (update.modicaClienteP(clienteP)) {//Realiza el Alta 
                JOptionPane.showMessageDialog(rootPane, "Actualizacion Exitosa");
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Ingresa un ID"); //valida que el campo id no este vacio
        }else{
            int id = Integer.parseInt(txtId.getText());
            ConsultasCliente eliminar = new ConsultasCliente();  //Se conecta a la Base de datos
            if (eliminar.eliminaCliente(id)) {
                JOptionPane.showMessageDialog(rootPane, "Se elimino este registro");
            }
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtId.setText("");
        txtNombre.setText("");
        txtApP.setText("");
        txtApM.setText("");
        txtMontoC.setText("");
        txtAdeudo.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnAgregar1;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnEliminar1;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiar1;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAdeudo;
    private javax.swing.JLabel lblApM;
    private javax.swing.JLabel lblApM1;
    private javax.swing.JLabel lblApP;
    private javax.swing.JLabel lblApP1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblId1;
    private javax.swing.JLabel lblMontoCredito;
    private javax.swing.JLabel lblMontoHC;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblPromo;
    private javax.swing.JLabel lblPromo1;
    private javax.swing.JPanel panelEstrella;
    private javax.swing.JPanel panelPreferente;
    private javax.swing.JTextField txtAdeudo;
    private javax.swing.JTextField txtApM;
    private javax.swing.JTextField txtApM1;
    private javax.swing.JTextField txtApP;
    private javax.swing.JTextField txtApP1;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtId1;
    private javax.swing.JTextField txtMontoC;
    private javax.swing.JTextField txtMontoH;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtPromo;
    private javax.swing.JTextField txtPromo1;
    // End of variables declaration//GEN-END:variables
}
